### ISSUE TITLE
Preparación de demo Epic 1

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#26]
Se requiere preparar la demo del Epic 1:

- [x] Adaptar la dapp para que por defecto dirija a `/avales`
- [x] Configurar la dapp para que funcione con la base de datos en Mongo Atlas.
- [x] Documentar y configurar en la wallet las direcciones de los usuarios Solicitante, Comerciante, Avalado y Avaldao.
- [x] Construir slices de la demo.
- [x] Crear claves publica y privada para conectarme al server beta. 
- [x] Desplegar smart contract en Testnet
